const mongoose = require('mongoose')
const { MONGODB_URI } = require('./config')
mongoose.connect(MONGODB_URI)
    .then(db => console.log('Mongodb conectado'))
    .catch(error => console.log(error))